baseURL: "https://www.santiagoferrer.mx"
title: Santiago Ferrer
paginate: 10
theme: PaperMod


buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: false

menu:
  main:
  - identifier: Categorias
    name: Categorias
    url: /categories/
    weight: 30
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 40
  - identifier: archives
    name: Archivos
    url: /archives/
    weight: 10
  - identifier: Search
    name: Busqueda
    url: /search/
    weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  
  GoogleAnalytics: G-GVM1X4NZTG
  
  analytics:
    google:
        SiteVerificationTag: "G-GVM1X4NZTG"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false 
  enableRobotsTXT: true
  hamBurgerMenu: true
  socialIcons: # optional
      - name: "twitter"
        url: "https://www.twitter.com/santiago_ferr/"
      - name: linkedin
        url: "https://www.linkedin.com/in/santiago-ferrer/"
      - name: buymeacoffee
        url: "https://www.buymeacoffee.com/santiagoferrer"


  profileMode:
    enabled: true
    title: "Santiago Ferrer" # optional default will be site title
    subtitle: "Hola probando, probando"
    imageUrl: /Profile Pic/PF_3.jpg # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 260 # custom size
    imageHeight: 260 # custom size

    buttons:
        - name: Blog
          url: "/blog"
        - name: Ensayos
          url: "/essays/"
        - name: Emprendedores
          url: "/business-interviews/"